---
name: Add someone to the Hyperledger GitHub org
about: request membership change
title: Add someone to GitHub
labels: New Hyperledger Member
assignees: davidwboswell, ryjones, SeanBohan

---

If you want to be able to assign bugs to someone, they only need **Read** access.

Please include:

* GitHub ID to add: 
* Project to be added to: 

One of:

* [Team to be added to](https://github.com/orgs/hyperledger/teams/0-hyperledger-contributors/teams):
* Role:
	- Read
	- Triage
	- Write
	- Manage
	- Admin
