---
name: Please publish packages to a new endpoint
about: publish a package
title: Please publish packages to a new endpoint
labels: publication
assignees: davidwboswell, ryjones, SeanBohan

---

Please include:

* GitHub repo:

* Endpoint:
