---
name: Create a new repo in the Hyperledger GitHub org
about: request new repo
title: Create a repo
labels: repo-ops
assignees: davidwboswell, ryjones, SeanBohan

---

Please include:

* GitHub repo to create:
* Project to be added to: 
* Teams with which access: (examples [on GitHub team list](https://github.com/orgs/hyperledger/teams))
	* Team name:
	* Role:
		- Read
		- Triage
		- Write
		- Manage
		- Admin
