---
name: Nomination
about: Nominate yourself to run for the TOC
title: "[NOMINATION]: Year and Name"
labels: "Nomination 2023"
assignees: ''

---

# Nomination 🗳️

## Nominee Name
<!--- Who is the nominee -->
<!--- Provide your GitHub handle -->

## Short Personal Bio
<!--- Provide a short bio on the nominee -->

## Short Personal Pitch
<!--- Provide why wishing to be a member of the TOC -->
