---
name: Remove a maintainer from a project
about: request maintainer change for a project
title: Remove a maintainer
labels: Remove Maintainer
assignees: davidwboswell, ryjones, SeanBohan

---

Please include:

* GitHub ID to removed: 
* Project to be removed from: 
