---
name: Transfer a repo to the Hyperledger GitHub org
about: request repo transfer
title: Transfer a repo
labels: repo-ops
assignees: davidwboswell, ryjones, SeanBohan

---

Please include:

* GitHub repo to transfer:
* Project to be added to: 
* Teams with which access: (examples [on GitHub team list](https://github.com/orgs/hyperledger/teams))
	* Team name:
	* Role:
		- Read
		- Triage
		- Write
		- Manage
		- Admin
